name: "PR is not marked as stale"

on:
  pull_request:
    types: [labeled, unlabeled]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.1.0
        with:
          REQUIRED_LABELS_ANY: ""
          REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label ['bug','enhancement','skip-changelog']"
          BANNED_LABELS: "stale"
