name: "Mark old PRs as stale"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          stale-pr-message: "This PR didnt change on the last 20 days. We're marking it as STALE. Before merging, pull develop or re-run the Jenkins job"
          days-before-stale: 0
